apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: ecommerce
    releaseName: ecommerce
    namespace: ecommerce
    valuesFile: values-prod.yaml
