apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.jwtRefreshSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.awsSecretAccessKey | quote }}
